export default [
  'front end development',
  'reactjs',
  'nodejs',
  'html5',
  'bootstrap5',
  'mongodb',
  'redux',
  'web development',
  'netlify',
  'graph ql',
  'javascript',
  'wordpress',
  'css3',
  'visual studio code',
  'github',
  'api',
  'semantic ui',
  'material ui',
  'angularjs',
  'sql',
  'linux',
  'react router',
  'serverless',
  'blockchain',
  'artificial intelligence',
  'progressive web app',
  'internet of things',
  'cyber security',
];
