export default [
  'front end development',
  'ben awad',
  'techlead',
  'reactjs',
  'nodejs',
  'html5',
  'bootstrap5',
  'mongodb',
  'redux',
  'web development',
  'scott hanselman',
  'netlify',
  'traversy media',
  'graph ql',
  'joma tech',
  'javascript',
  'wordpress',
  'css3',
  'visual studio code',
  'github',
];
